trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
- group: TerraformSPN

steps:
- script: echo Deploy NGINX
  displayName: 'Starting Job'

- task: TerraformInstaller@0
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  displayName: Terraform Initialization
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrate/nginx'
    backendType: 'azurerm'
    backendServiceArm: 'AzuretoAzureDevOps'
    backendAzureRmResourceGroupName: 'terraformbackend'
    backendAzureRmStorageAccountName: 'azurebackendterrstracc'
    backendAzureRmContainerName: 'backendcontainer'
    backendAzureRmKey: 'nginxdev.tfstate'

- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrate/nginx'
    environmentServiceName: 'AzuretoAzureDevOps'
    commandOptions: '-var-file ../globalvars.tfvars'
