pool:
  vmImage: 'vs2017-win2016'

variables:
- group: TerraformSPN

steps:
- script: echo Deploy NGINX
  displayName: 'Starting Job'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  inputs:
    terraformVersion: 'v0.12.18'

- task: TerraformCLI@0
  displayName: Terraform Initialization
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrate/nginx'
    backendType: 'azurerm'
    backendServiceArm: 'AzuretoAzureDevOps'
    backendAzureRmResourceGroupName: 'terraformbackend'
    backendAzureRmStorageAccountName: 'azurebackendterrstracc'
    backendAzureRmContainerName: 'backendcontainer'
    backendAzureRmKey: 'nginxdev.tfstate'

- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrate/nginx'
    environmentServiceName: 'AzuretoAzureDevOps'
    commandOptions: '-var-file ../globalvars.tfvars'

- task: TerraformCLI@0
  displayName: Terraform Apply
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrate/nginx'
    environmentServiceName: 'AzuretoAzureDevOps'
    commandOptions: '-var-file ../globalvars.tfvars'