trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: TerraformSPN

steps:
- script: echo Deploy NGINX
  displayName: 'Run a one-line script'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrate/nginx'
    backendType: 'azurerm'
    backendServiceArm: 'AzuretoAzureDevOps'
    backendAzureRmResourceGroupName: 'terraformbackend'
    backendAzureRmStorageAccountName: 'azurebackendterrstracc'
    backendAzureRmContainerName: 'backendcontainer'
    backendAzureRmKey: 'nginxdev.tfstate'

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrate/nginx'
    environmentServiceName: 'AzuretoAzureDevOps'
    commandOptions: '-var-file ../globalvars.tfvars'
