
trigger: none

pool:
  vmImage: 'vs2017-win2016'

stages:
- stage: Destroy
  displayName: Destroy stage
  jobs:
  - deployment: DeployVM
    displayName: Destroy Nginx VM
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
            inputs:
              terraformVersion: 'v0.12.18'

          - task: TerraformCLI@0
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrate/nginxV2'
              backendType: 'azurerm'
              backendServiceArm: 'serviceconnection'
              backendAzureRmResourceGroupName: 'terraformDemo-rg'
              backendAzureRmStorageAccountName: 'demotfbackend'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'nginxdev.tfstate'

          - task: TerraformCLI@0
            displayName: Terraform Destroy
            inputs:
              command: 'destroy'
              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrate/nginxV2'
              environmentServiceName: 'serviceconnection'
              commandOptions: '-var-file ./globalvars/nginxDev.tfvars'
